SELECT TYPE, NAME, BIRTHDAY
FROM (
    SELECT 'YOUNGEST' AS TYPE, NAME, BIRTHDAY
    FROM worker
    ORDER BY BIRTHDAY DESC
    LIMIT 1
) AS youngest

UNION ALL

SELECT TYPE, NAME, BIRTHDAY
FROM (
    SELECT 'OLDEST' AS TYPE, NAME, BIRTHDAY
    FROM worker
    ORDER BY BIRTHDAY ASC
    LIMIT 1
) AS oldest;